### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by CinciRyan** [mdegat01/addon-amr2mqtt#105]
I'm receiving the error "ValueError: invalid literal for int() with base 10: ''" when starting amr2mqtt add-on in Home Assistant 2024.1.3

Is this add-on still being produced / supported?

**To Reproduce**
Start the add-on

**Logs**
```
AMR2MQTT
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh

-----------------------------------------------------------
 Add-on: AMR2MQTT
 AMR2MQTT for Home Assistant
-----------------------------------------------------------
 Add-on version: 2.1.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.1.3
 Home Assistant Supervisor: 2023.12.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Log level is set to DEBUG
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[12:44:02] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/30-config.sh
[12:44:02] DEBUG: Validate config and look for suggestions
[12:44:03] DEBUG: Requested API resource: http://supervisor/services/mqtt
[12:44:03] DEBUG: Request method: GET
[12:44:03] DEBUG: Request data: {}
[12:44:03] DEBUG: API HTTP Response code: 400
[12:44:03] DEBUG: API Response: {"result": "error", "message": "Service not enabled"}

[12:44:03] ERROR: Got unexpected response from the API: Service not enabled
[12:44:03] INFO: Ensure MQTT broker is reachable at : (60s timeout)
cont-init: info: /etc/cont-init.d/30-config.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun amr2mqtt (no readiness notification)
services-up: info: copying legacy longrun rtl_tcp (no readiness notification)
s6-rc: info: service legacy-services successfully started
[12:45:03] DEBUG: Setting MQTT details...
[12:45:03] INFO: Starting rtl_tcp daemon...
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000406

Using device 0: Generic RTL2832U OEM
Found Elonics E4000 tuner
[12:45:03] INFO: Log level set to DEBUG
[12:45:03] INFO: Waiting for rtl_tcp...
Tuned to 100000000 Hz.
Allocating 15 zero-copy buffers
[12:45:04] INFO: Handing over control to AMR2MQTT...
Traceback (most recent call last):
  File "/amr2mqtt/amr2mqtt.py", line 18, in <module>
    import settings
  File "/amr2mqtt/settings.py", line 32, in <module>
    MQTT_PORT = int(os.environ.get("MQTT_PORT"))
ValueError: invalid literal for int() with base 10: ''
Signal caught, exiting!
Signal caught, exiting!
[12:45:04] WARNING: Halt add-on with exit code 1
s6-rc: info: service legacy-services: stopping
[12:45:04] INFO: Service restart after closing
[12:45:04] INFO: Service restart after closing
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
Signal caught, exiting!

```
This does NOT cause the add-on to stop.

**Environment (please complete the following information):**

- Add-on version: 2.1.2     // it appears this version, according to Github, is 30 Aug 2022
- Supervisor version: 2023.12.0
- Operating system: 2024.1.3

**Comment by CinciRyan** [comment]
@mdegat01

**Comment by CinciRyan** [comment]
Invalid MQTT configuration.  Please better document this in the add-on documentation. I found the correct settings via a posting in the HA Community forum.
